// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/AcidPrint.tsx": () => import("../components/mockups/hero-variants/AcidPrint.tsx"),
  "./components/mockups/hero-variants/Broadcast.tsx": () => import("../components/mockups/hero-variants/Broadcast.tsx"),
  "./components/mockups/hero-variants/Incandescent.tsx": () => import("../components/mockups/hero-variants/Incandescent.tsx")
};
